# This workflow tests the project by running a full build with the 'release' profile.
# It also performs GPG signing if the required secrets are available.

name: Test Release Build

permissions:
  contents: read # to fetch code (actions/checkout)
  pull-requests: read # to read PR metadata

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          # The action will automatically cache Maven dependencies in the GitHub Actions cache
          cache: 'maven'
          # The action will copy the GPG keys to the correct location inside the github runner
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          # The action will set the server credentials in the Maven settings.xml according to Maven Central requirements
          # Username and password are the name of the environment variable that will hold the secret value giben in the 
          # 'Build with Maven' step as environment variables
          server-id: maven-central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD

      - name: Build with Maven
        run: sh mvnw clean deploy -P release --batch-mode
        env:
          # The maven pgp plugin assumes the passphrase is provided in an env variable named MAVEN_GPG_PASSPHRASE
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          # The actions/setup-java@v5 has configured the settings.xml server credentials using placeholders that
          # read values from environment variable names provided in the 'server-username' and 'server-password' inputs
          # int eh 'Set up JDK 8' step.
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
